### ISSUE TITLE
Multiple line comment parsing issue (C/C++)

### ISSUE THREAD

**Issue by jice73** [Gruntfuggly/bettercomment#13]
I am seeing this with version 0.0.12 in Visual Studio Code.  There seems to be a parsing issue with the following (I tried to simplify it as much as possible):

```c++
//* This is a single line comment.
void foo()
{
    do_something();
    /*comment*/
}
```

While attempting to comment out the do_something(); line, Better Comment is instead removing '/\*' from '//* This', and the trailing '*/' from '/\*comment\*/'.

I was expecting the 'do_something();' line to become '// do_something();'.

**Comment by Gruntfuggly** [comment]
I think that will cause problems for the extension because it searches backwards from the cursor position for `/*` and forward for `*/` so in this case it will think it inside a larger comment. 

It would probably need to check that the line containing the opening comment marker isn't itself commented out.

The problem is that it's quite a naive algorithm - using regexes for processing C/C++ is really a bad idea, and it should really be done with a proper parser, but that would be a different proposition for the extension altogether.

I'll see if I can add a simple check, but there may still be other edge cases.

**Comment by Gruntfuggly** [comment]
OK, please give the latest version a try (0.0.14). It's a bit of a hack for now, but it worked in my testing.

**Comment by jice73** [comment]
Wow, that was fast.  I just tried 0.0.14, and it seems to be working for me.

Thanks so much for fixing my favourite comment extension for C++/CMake/XML!!  Going to close this, thanks muchly sir!  :)
